import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: {
          DEFAULT: "var(--color-background-default)",
          elevated: "var(--color-background-elevated)",
          subtle: "var(--color-background-subtle)",
          interactive: "var(--color-background-interactive)",
          inverse: "var(--color-background-inverse)",
        },
        content: {
          DEFAULT: "var(--color-text-default)",
          muted: "var(--color-text-muted)",
          subtle: "var(--color-text-subtle)",
          inverse: "var(--color-text-inverse)",
          brand: "var(--color-text-brand)",
          success: "var(--color-text-success)",
          warning: "var(--color-text-warning)",
          error: "var(--color-text-error)",
        },
        line: {
          DEFAULT: "var(--color-border-default)",
          strong: "var(--color-border-strong)",
          focus: "var(--color-border-focus)",
          success: "var(--color-border-success)",
          warning: "var(--color-border-warning)",
          error: "var(--color-border-error)",
        },
        action: {
          primary: "var(--color-action-primary)",
          "primary-hover": "var(--color-action-primary-hover)",
          "primary-active": "var(--color-action-primary-active)",
          "primary-text": "var(--color-action-primary-text)",
          secondary: "var(--color-action-secondary)",
          "secondary-hover": "var(--color-action-secondary-hover)",
          danger: "var(--color-action-danger)",
          "danger-hover": "var(--color-action-danger-hover)",
        },
        status: {
          "success-bg": "var(--color-status-success-background)",
          "success-border": "var(--color-status-success-border)",
          "success-text": "var(--color-status-success-text)",
          "warning-bg": "var(--color-status-warning-background)",
          "warning-border": "var(--color-status-warning-border)",
          "warning-text": "var(--color-status-warning-text)",
          "error-bg": "var(--color-status-error-background)",
          "error-border": "var(--color-status-error-border)",
          "error-text": "var(--color-status-error-text)",
          "info-bg": "var(--color-status-info-background)",
          "info-border": "var(--color-status-info-border)",
          "info-text": "var(--color-status-info-text)",
        },
        data: {
          primary: "var(--color-data-primary)",
          efficient: "var(--color-data-efficient)",
          warning: "var(--color-data-warning)",
          grid: "var(--color-data-grid)",
          remaining: "var(--color-data-remaining-material)",
          "stage-1": "var(--color-data-stage-1)",
          "stage-2": "var(--color-data-stage-2)",
          "stage-3": "var(--color-data-stage-3)",
          "stage-4": "var(--color-data-stage-4)",
          "stage-5": "var(--color-data-stage-5)",
          "stage-6": "var(--color-data-stage-6)",
        },
      },
      fontFamily: {
        sans: ["var(--font-geist-sans)", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["var(--font-geist-mono)", "ui-monospace", "SFMono-Regular", "Consolas", "monospace"],
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
      },
      boxShadow: {
        raised: "var(--shadow-raised)",
        overlay: "var(--shadow-overlay)",
      },
      transitionDuration: {
        fast: "var(--motion-fast)",
        standard: "var(--motion-standard)",
        slow: "var(--motion-slow)",
      },
      transitionTimingFunction: {
        standard: "var(--ease-standard)",
      },
      maxWidth: {
        narrow: "48rem",
        content: "70rem",
        wide: "80rem",
      },
    },
  },
  plugins: [],
} satisfies Config;
